### ISSUE TITLE
YAML for configuration file

### ISSUE THREAD

**Issue by pavel-odintsov** [pavel-odintsov/fastnetmon#378]
As mentioned in ticket https://github.com/FastVPSEestiOu/fastnetmon/issues/377 Henry Spanka want YAML support for configuration files.

**Comment by henry-spanka** [comment]
Well. From my point of view, YAML is much more readable as JSON. On the other hand, you can also
split json objects over multiple lines so it's nicer.

With YAML, we could to something like the following example:

```
logging:
  local: yes
  remote: yes
  remoteservers:
    - 10.0.0.1
    - 172.16.0.1

limits:
  - 172.16.0.0/16:
      flows: 100
      mbps: 50
      pps: 10000
  - 10.0.0.0/8:
      flows: 200
      mbps: 10
      pps: 5000
```

Would be very readable and it's easier to declare host groups and probably we can access this data
in a better way in C than parsing just strings like we do now.
